name: Build and publish

on:
  workflow_dispatch:
  push:
    paths:
      - workspaces/www/lib/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: workspaces/www/lib
          clean: true
