name: Build statusboard

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, fetch & build
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run fetch
          npm run build
      - name: Commit/Push Files
        run: |
          # Git Commands
          git config --local user.email "ops+npm-deploy-user@npmjs.com"
          git config --local user.name "beep boop I am a robot"
          git commit -m "feat: build changes" -a
          git push origin master
