name: Build statusboard
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: npm install, fetch & build
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run fetch
      - name: Fetch & Store Data
        run: |
          # Git Commands
          git config --local user.email "ops+npm-deploy-user@npmjs.com"
          git config --local user.name "npm cli ops bot"
          git add .
          git commit -m "chore: store fetched data"
          git push origin main
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
