name: Build statusboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.email "npm-cli+bot@github.com"
          git config --global user.name "npm CLI robot"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Update npm to latest
        run: npm i --prefer-online --no-fund --no-audit -g npm@latest
      - run: npm -v
      - run: npm i --ignore-scripts --no-audit --no-fund --package-lock
      - run: npm run fetch:data
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit data
        run: |
          git add .
          git commit -m "chore: update data"
          git push origin main
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          clean: true
