name: Build statusboard
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Fetch data
        run: npm run fetch
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store data
        run: |
          # Git Commands
          git config --local user.email "ops+npm-deploy-user@npmjs.com"
          git config --local user.name "npm cli ops bot"
          git add .
          git commit -m "chore: store fetched data"
          git push origin main
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          clean: true
