name: Test out publish call

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  publish:
    needs: fetch
    uses: ./.github/workflows/publish.yml@main
