name: Publish

on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    # Check out the content (source branch)
    - name: Check out source
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: Update npm to latest
      run: npm i --prefer-online --no-fund --no-audit -g npm@latest
    - run: npm -v
    - run: npm i --ignore-scripts --no-audit --no-fund --package-lock
    - run: npm run build -w www
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './workspaces/www/build'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    outputs:
      deployment_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          preview: ${{ github.event_name == 'pull_request_target' }}
