name: Sync repository labels
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-sync-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node deps and run `sync-labels`
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run sync-labels
      - name: Commit and push unique labels
        run: |
          # Git Commands
          git config --local user.email "ops+robot@npmjs.com"
          git config --local user.name "npm-robot"
          git add .
          git commit -m "chore: commit unique label set"
          git push origin latest
