name: Sync maintained repo list

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: "Sync maintained repo list"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: npm install
        run: |
          npm ci
      - name: update maintained list
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run maintained
      - name: Commit changes
        run: |
          git config --local user.email "ops+npm-deploy-user@npmjs.com"
          git config --local user.name "npm cli ops bot"
          git add .
          git commit -m "fix: update maintained list" && git push origin main || echo "nothing to commit"
